server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:file:./Database/beerhouse;MODE=LEGACY
    username: beerkeeper
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update